version: '3.1'

services:
  stellar-spectra-api:
    image: stellar-spectra/stellar-spectra.api:head
    container_name: 'stellar-spectra-api'
    restart: always
    ports:
      - 3000:3000
    environment:
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
  stellar-spectra-front:
    image: stellar-spectra/stellar-spectra.front:head
    container_name: 'stellar-spectra-front'
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - stellar-spectra-api